---
- name: Instalar Java, csh e configurar usuário ctmuser
  hosts: localhost
  become: true
  gather_facts: no

  tasks:
    - name: Atualizar cache dos repositórios
      ansible.builtin.dnf:
        update_cache: yes

    - name: Instalar Java e csh
      ansible.builtin.dnf:
        name:
          - java-17-openjdk
          - csh
        state: present

    - name: Criar grupo controlm
      ansible.builtin.group:
        name: controlm
        state: present

    - name: Criar diretório /ctmuser (sem ownership ainda)
      ansible.builtin.file:
        path: /ctmuser
        state: directory
        mode: '0755'

    - name: Criar usuário ctmuser com home /ctmuser e shell csh
      ansible.builtin.user:
        name: ctmuser
        group: controlm
        shell: /bin/csh
        home: /ctmuser
        create_home: no
        state: present

    - name: Ajustar permissões do diretório /ctmuser
      ansible.builtin.file:
        path: /ctmuser
        owner: ctmuser
        group: controlm
        mode: '0755'
        state: directory
